global_planner_name: "hybrid_planning_demo/GlobalMTCPlannerComponent"
planning_scene_monitor_options:
  monitored_planning_scene_topic: "planning_scene"
planning_pipelines:
  pipeline_names: ["pilz_industrial_motion_planner"] #["ompl"]
  namespace: ""
