
robot_description: "robot_description"
group_name: "ur_manipulator"
trajectory_operator_plugin_name: "hybrid_planning_demo::SimpleServoSampler"
local_constraint_solver_plugin_name: "hybrid_planning_demo::ServoSolver"
local_planning_frequency: 100.0
global_solution_topic: "global_trajectory"
local_solution_topic: "/joint_trajectory_controller/joint_trajectory_NOT_HERE"
local_solution_topic_type: "trajectory_msgs/JointTrajectory" # or "std_msgs/Float64MultiArray"

# SimpleSampler param
pass_through: false

# ForwardTrajectory param
stop_before_collision: true

# ServoSolver param
velocity_scaling_threshold: 0.1
